version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: atividadesbd_postgres
    environment:
      POSTGRES_DB: atividadesbd
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: atividadesbd_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
